-- Boilerplate snippets for common Odoo Python patterns, expanded via LuaSnip
-- (:help luasnip). Trigger the word, then hit the expand key from SECTION 8.

local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets('python', {
  s('omodel', {
    t 'class ',
    i(1, 'ModelName'),
    t '(models.Model):',
    t { '', '    _name = "' },
    i(2, 'model.name'),
    t '"',
    t { '', '    _description = "' },
    i(3, 'Description'),
    t '"',
    t { '', '', '    ' },
    i(0),
  }),

  s('ochar', { t 'fields.Char(string="', i(1, 'Label'), t '"', i(0), t ')' }),
  s('otext', { t 'fields.Text(string="', i(1, 'Label'), t '"', i(0), t ')' }),
  s('oint', { t 'fields.Integer(string="', i(1, 'Label'), t '"', i(0), t ')' }),
  s('obool', { t 'fields.Boolean(string="', i(1, 'Label'), t '"', i(0), t ')' }),

  s('om2o', {
    t 'fields.Many2one("',
    i(1, 'res.partner'),
    t '", string="',
    i(2, 'Label'),
    t '"',
    i(0),
    t ')',
  }),
  s('oo2m', {
    t 'fields.One2many("',
    i(1, 'model.name'),
    t '", "',
    i(2, 'inverse_field_id'),
    t '", string="',
    i(3, 'Label'),
    t '"',
    i(0),
    t ')',
  }),
  s('om2m', {
    t 'fields.Many2many("',
    i(1, 'res.partner'),
    t '", string="',
    i(2, 'Label'),
    t '"',
    i(0),
    t ')',
  }),
  s('osel', {
    t 'fields.Selection([("',
    i(1, 'key'),
    t '", "',
    i(2, 'Label'),
    t '")], string="',
    i(3, 'Label'),
    t '"',
    i(0),
    t ')',
  }),

  s('odepends', {
    t '@api.depends("',
    i(1, 'field_id'),
    t '")',
    t { '', '    def _compute_' },
    i(2, 'name'),
    t '(self):',
    t { '', '        for record in self:', '            ' },
    i(0),
  }),
  s('oconstrains', {
    t '@api.constrains("',
    i(1, 'field_id'),
    t '")',
    t { '', '    def _check_' },
    i(2, 'name'),
    t '(self):',
    t { '', '        for record in self:', '            ' },
    i(0),
  }),
  s('oonchange', {
    t '@api.onchange("',
    i(1, 'field_id'),
    t '")',
    t { '', '    def _onchange_' },
    i(2, 'name'),
    t '(self):',
    t { '', '        ' },
    i(0),
  }),

  s('omanifest', {
    t { '{', '    "name": "' },
    i(1, 'Module Name'),
    t '"',
    t { '', '    "version": "19.0.1.0.0",', '    "category": "' },
    i(2, 'Uncategorized'),
    t '"',
    t { '', '    "summary": "' },
    i(3, ''),
    t '"',
    t { '', '    "author": "' },
    i(4, 'Arrowhitech'),
    t '"',
    t { '', '    "depends": [', '        "' },
    i(5, 'base'),
    t '"',
    t { '', '    ],', '    "data": [', '        "' },
    i(6, 'security/ir.model.access.csv'),
    t '"',
    t { '', '    ],', '    "installable": True,', '    "application": ' },
    i(7, 'False'),
    t { '', '}' },
    i(0),
  }),
})
